imports:
- path: hlflb.py

# In the resources section below, the properties of the resources are replaced
# with the names of the templates.
resources:
- name: hlf-load-balancer
  type: hlflb.py
  properties:
    loadBalancerIP: '34.98.90.83'
    project: 'yongssandbox'
    zones: ['us-west1-a', 'us-west1-b', 'us-west1-c']
    clusterName: 'ibcdev-cluster'
    firewallSourceRange: ['209.85.152.0/22', '209.85.204.0/22', '35.191.0.0/16', '130.211.0.0/22']
    gcpCredentialFile: 'serviceaccount.json'
