{{/* Service Template for Orderer/Peer Nodes. Expect currOrg, currHlfNodeType and global to be passed in */}}
{{- define "hlf-network.services" }}

{{- $org := .currOrg }}
{{- $hlfNodeType := .currHlfNodeType }}
{{- $ := .global }}
{{- $exponseOrgLevelService := or (eq $hlfNodeType "orderer") $.Values.hlfLoadBalancePeerNodes }}
{{- $exponseNodeLevelService := eq $hlfNodeType "peer" }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $org.Name | lower }}
  namespace: {{ $.Values.hlfNetworkNamespace }}
  labels:
    purpose: org-level-headless-for-internal-dns
spec:
  clusterIP: None
  selector:
    app: {{ $hlfNodeType }}Pod
    org: {{ $org.Name }}
---

{{- if $exponseOrgLevelService }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $org.Name | lower }}-cluster-nodeport
  namespace: {{ $.Values.hlfNetworkNamespace }}
  labels:
    purpose: org-level-cluster-nodeport-for-load-balancer
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    service.alpha.kubernetes.io/app-protocols: '{"grpc":"HTTP2"}'
    beta.cloud.google.com/backend-config: '{"ports": {"grpc":"grpc-backendconfig"}}'    
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: {{ $hlfNodeType }}Pod
    org: {{ $org.Name }}
---
{{- end }} {{- /* if */ -}}

{{- range $i, $host := $org.Specs }}
{{- if $exponseNodeLevelService }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $org.Name | lower }}-{{ $host.Hostname | lower }}-cluster-nodeport
  namespace: {{ $.Values.hlfNetworkNamespace }}
  labels:
    purpose: node-level-cluster-nodeport-for-load-balancer
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
    service.alpha.kubernetes.io/app-protocols: '{"grpc":"HTTP2"}'
    beta.cloud.google.com/backend-config: '{"ports": {"grpc":"grpc-backendconfig"}}'
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: {{ $hlfNodeType }}Pod
    org: {{ $org.Name }}
    statefulset.kubernetes.io/pod-name: {{ $org.Name | lower }}{{ $host.Hostname | lower }}
---
{{- end }} {{- /* if */ -}}
{{- end }} {{- /* org.Specs */ -}}{{""}}

{{- end }}
