{{- $mc := dict "certs" (list) -}}
{{- range $i, $org := $.Values.OrdererOrgs }}
{{- $noop := printf "hlf-cert-%s"  $org.Name | lower  | append $mc.certs | set $mc "certs" -}}
{{- end -}}
{{- range $i, $org := $.Values.PeerOrgs }}
{{- $noop := printf "hlf-cert-%s" $org.Name | lower  | append $mc.certs | set $mc "certs" -}}
{{- range $i, $host := $org.Specs }}
{{- $noop := printf "hlf-cert-%s-%s" $org.Name $host.Hostname | lower  | append $mc.certs | set $mc "certs" -}}
{{- end -}}
{{- end -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hlf-ingress
  namespace: {{ $.Values.hlfNetworkNamespace }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hlf-load-balancer-static-ip
    networking.gke.io/managed-certificates: {{- " " -}}{{- join "," $mc.certs -}}{{""}}
  labels:
    purpose: hlf-network-ingress-for-lb
spec:
  rules:
  {{- range $i, $org := $.Values.OrdererOrgs }}
  - host: {{ $org.Domain | lower }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ $org.Name | lower }}-cluster-nodeport
          servicePort: 443
  {{- range $i, $host := $org.Specs }}
  - host: {{ $host.Hostname | lower }}.{{ $org.Domain | lower }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ $org.Name | lower }}-{{ $host.Hostname | lower }}-cluster-nodeport
          servicePort: 443
  {{- end }} {{- /* org.Specs */ -}}
  {{- end }} {{- /* OrdererOrgs */ -}}

  {{- range $i, $org := $.Values.PeerOrgs }}
  - host: peer.{{ $org.Domain | lower }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ $org.Name | lower }}-cluster-nodeport
          servicePort: 443
  {{- range $i, $host := $org.Specs }}
  - host: {{ $host.Hostname | lower }}.{{ $org.Domain | lower }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ $org.Name | lower }}-{{ $host.Hostname | lower }}-cluster-nodeport
          servicePort: 443
  {{- end }} {{- /* org.Specs */ -}}
  {{- end }} {{- /* PeerOrgs */ -}}
