{{- if $.Values.hlfCreateSSLCerts }}
{{- range $i, $org := $.Values.OrdererOrgs }}
{{- if $.Values.hlfLoadBalancePeerNodes }}
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: hlf-cert-{{ $org.Name | lower }}
  namespace: {{ $.Values.hlfNetworkNamespace }}
spec:
  domains:
    - {{ $org.Domain | lower }}
---
{{- end }}
{{- range $i, $host := $org.Specs }}
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: hlf-cert-{{ $org.Name | lower }}-{{ $host.Hostname | lower }}
  namespace: {{ $.Values.hlfNetworkNamespace }}
spec:
  domains:
    - {{ $host.Hostname | lower }}.{{ $org.Domain | lower }}
---
{{- end }} {{- /* org.Specs */ -}}
{{- end }} {{- /* OrdererOrgs */ -}}{{""}}


{{- range $i, $org := $.Values.PeerOrgs }}

{{- if $.Values.hlfCAEnabled }}
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: hlf-cert-{{ $org.Name | lower }}-ca
  namespace: {{ $.Values.hlfNetworkNamespace }}
spec:
  domains:
    - ca.{{ $org.Domain | lower }}
---
{{- end }}

{{- if $.Values.hlfLoadBalancePeerNodes }}
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: hlf-cert-{{ $org.Name | lower }}
  namespace: {{ $.Values.hlfNetworkNamespace }}
spec:
  domains:
    - peer.{{ $org.Domain | lower }}
---
{{- end }}
{{- range $i, $host := $org.Specs }}
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: hlf-cert-{{ $org.Name | lower }}-{{ $host.Hostname | lower }}
  namespace: {{ $.Values.hlfNetworkNamespace }}
spec:
  domains:
    - {{ $host.Hostname | lower }}.{{ $org.Domain | lower }}
---
{{- end }} {{- /* org.Specs */ -}}
{{- end }} {{- /* PeerOrgs */ -}}{{""}}
{{- end }} {{- /* $.Values.hlfCreateSSLCerts */ -}}
