{{- $mc := dict "certs" (list) -}}
{{- range $i, $org := $.Values.OrdererOrgs }}
{{- $noop := printf "hlf-cert-%s"  $org.Name | lower  | append $mc.certs | set $mc "certs" -}}
{{- end -}}
{{- range $i, $org := $.Values.PeerOrgs }}
{{- if $.Values.hlfCAEnabled }}
{{- $noop := printf "hlf-cert-%s-ca" $org.Name | lower  | append $mc.certs | set $mc "certs" -}}
{{- end -}}
{{- if $.Values.hlfLoadBalancePeerNodes }}
{{- $noop := printf "hlf-cert-%s" $org.Name | lower  | append $mc.certs | set $mc "certs" -}}
{{- end -}}
{{- range $i, $host := $org.Specs }}
{{- $noop := printf "hlf-cert-%s-%s" $org.Name $host.Hostname | lower  | append $mc.certs | set $mc "certs" -}}
{{- end -}}
{{- end -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hlf-ingress
  namespace: {{ $.Values.hlfNetworkNamespace }}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: {{ $.Values.hlfLBStaticIPName }}
    networking.gke.io/managed-certificates: {{- " " -}}{{- join "," $mc.certs -}}{{""}}
  labels:
    purpose: hlf-network-ingress-for-lb
spec:
  rules:
  {{- range $i, $org := $.Values.OrdererOrgs }}
  - host: {{ $org.Domain | lower }}
    http:
      paths:
      - path: /healthz
        backend:
          serviceName: {{ $org.Name | lower }}-cluster-nodeport
          servicePort: 8443
      - path: /*
        backend:
          serviceName: {{ $org.Name | lower }}-cluster-nodeport
          servicePort: 443
  {{- end }} {{- /* OrdererOrgs */ -}}
  {{- range $i, $org := $.Values.PeerOrgs }} 
  {{- if $.Values.hlfCAEnabled }}
  - host: ca.{{ $org.Domain | lower }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ $org.Name | lower }}-ca-cluster-nodeport
          servicePort: 443
  {{- end }}
  {{- if $.Values.hlfLoadBalancePeerNodes }}
  - host: peer.{{ $org.Domain | lower }}
    http:
      paths:
      - path: /healthz
        backend:
          serviceName: {{ $org.Name | lower }}-cluster-nodeport
          servicePort: 8443
      - path: /*
        backend:
          serviceName: {{ $org.Name | lower }}-cluster-nodeport
          servicePort: 443
  {{- end }}
  {{- range $i, $host := $org.Specs }}
  - host: {{ $host.Hostname | lower }}.{{ $org.Domain | lower }}
    http:
      paths:
      - path: /healthz
        backend:
          serviceName: {{ $org.Name | lower }}-{{ $host.Hostname | lower }}-cluster-nodeport
          servicePort: 8443
      - path: /*
        backend:
          serviceName: {{ $org.Name | lower }}-{{ $host.Hostname | lower }}-cluster-nodeport
          servicePort: 443
  {{- end }} {{- /* org.Specs */ -}}
  {{- end }} {{- /* PeerOrgs */ -}}
