apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: grpc-backendconfig
  namespace: {{ $.Values.hlfNetworkNamespace }}
spec:
  timeoutSec: 600
  connectionDraining:
    drainingTimeoutSec: 60