apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-genesis.block
  namespace: {{ $.Values.hlfNetworkNamespace }}
data:
  genesis.block: |-
      {{ $.Files.Get "channel-artifacts/genesis.block" | b64enc }}
